//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KD.PKOL.TestClient
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageRequest", Namespace="http://schemas.datacontract.org/2004/07/KD.PKOL.Models.MessageService")]
    [System.SerializableAttribute()]
    public partial class MessageRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KD.PKOL.TestClient.Recipient RecipientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KD.PKOL.TestClient.Recipient Recipient
        {
            get
            {
                return this.RecipientField;
            }
            set
            {
                this.RecipientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipient", Namespace="http://schemas.datacontract.org/2004/07/KD.PKOL.Models.MessageService")]
    [System.SerializableAttribute()]
    public partial class Recipient : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KD.PKOL.TestClient.Contact[] ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KD.PKOL.TestClient.LegalForm LegalFormField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KD.PKOL.TestClient.Contact[] Contacts
        {
            get
            {
                return this.ContactsField;
            }
            set
            {
                this.ContactsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KD.PKOL.TestClient.LegalForm LegalForm
        {
            get
            {
                return this.LegalFormField;
            }
            set
            {
                this.LegalFormField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/KD.PKOL.Models.MessageService")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KD.PKOL.TestClient.ContactType ContactTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KD.PKOL.TestClient.ContactType ContactType
        {
            get
            {
                return this.ContactTypeField;
            }
            set
            {
                this.ContactTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LegalForm", Namespace="http://schemas.datacontract.org/2004/07/KD.PKOL.Models.MessageService")]
    public enum LegalForm : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Person = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Company = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactType", Namespace="http://schemas.datacontract.org/2004/07/KD.PKOL.Models.MessageService")]
    public enum ContactType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mobile = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fax = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OfficePhone = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OfficeFax = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OfficeEmail = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageResponse", Namespace="http://schemas.datacontract.org/2004/07/KD.PKOL.Models.MessageService")]
    [System.SerializableAttribute()]
    public partial class MessageResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KD.PKOL.TestClient.ReturnCode ReturnCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KD.PKOL.TestClient.ReturnCode ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnCode", Namespace="http://schemas.datacontract.org/2004/07/KD.PKOL.Models.MessageService")]
    public enum ReturnCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KD.PKOL.TestClient.IMessageService")]
    public interface IMessageService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Send", ReplyAction="http://tempuri.org/IMessageService/SendResponse")]
        KD.PKOL.TestClient.MessageResponse Send(KD.PKOL.TestClient.MessageRequest message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Send", ReplyAction="http://tempuri.org/IMessageService/SendResponse")]
        System.Threading.Tasks.Task<KD.PKOL.TestClient.MessageResponse> SendAsync(KD.PKOL.TestClient.MessageRequest message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceChannel : KD.PKOL.TestClient.IMessageService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceClient : System.ServiceModel.ClientBase<KD.PKOL.TestClient.IMessageService>, KD.PKOL.TestClient.IMessageService
    {
        
        public MessageServiceClient()
        {
        }
        
        public MessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public KD.PKOL.TestClient.MessageResponse Send(KD.PKOL.TestClient.MessageRequest message)
        {
            return base.Channel.Send(message);
        }
        
        public System.Threading.Tasks.Task<KD.PKOL.TestClient.MessageResponse> SendAsync(KD.PKOL.TestClient.MessageRequest message)
        {
            return base.Channel.SendAsync(message);
        }
    }
}
